/// Flutter icons GuestInMe
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  GuestInMe
///      fonts:
///       - asset: fonts/GuestInMe.ttf
///
/// 
/// * Linearicons Free, Copyright (C) Linearicons.com
///         Author:    Perxis
///         License:   CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)
///         Homepage:  https://linearicons.com
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class GuestInMe {
  GuestInMe._();

  static const _kFontFam = 'GuestInMe';
  static const _kFontPkg = null;

  static const IconData diamond = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_2 = IconData(0xe845, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_3 = IconData(0xe992, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diamond_1 = IconData(0xf219, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
